import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    // 'hello',
    {
      type: 'category',
      label: 'Результаты эксперимента',
      link: {
        "type": "generated-index",
        "description": "В данном разделе содержатся таблицы с результатами экспериментов по исследованию оптимизации производительности рендеринга компонентов"
      },
      items: [
        'results/components-creation',
        'results/components-update',
      ],
    },
    {
      type: 'category',
      label: 'Графики',
      link: {
        "type": "generated-index",
        "description": "В данном разделе содержатся графики с результатами экспериментов по исследованию оптимизации производительности рендеринга компонентов"
      },
      items: [
        'charts/components-creation-charts',
        'charts/components-update-charts'
      ],
    },
    {
      type: 'doc',
      id: 'recommendations',
      label: 'Рекомендации'
    }
    // {
    //   type: 'category',
    //   label: 'Рекомендации',
    //   items: [
    //       'recommendations'
    //   ]
    // },
  ],
};

export default sidebars;
